### ISSUE TITLE
Please add a license for others to fork and work on it.

### ISSUE THREAD

**Issue by ProxyNeko** [daveyliam/anvilmapper#2]
Might we request a license be added to this and MapWriter so that myself or others can port these to newer versions of Minecraft.

Without a license we can't port this or publish it to CurseForge (the new mod launcher/distributor modders and players use now to play modpacks and share mods) and maintain it without it breaking licenses and such.

https://choosealicense.com/

Hope you are well and that we hear back soon so that we can bring back this great old mod!

**Comment by daveyliam** [comment]
Done, added MIT license to anvilmapper and mapwriter repos.
Thanks for letting me know! Had no idea people were still interested and the lack of a proper license was causing issues.
Wish there was an easy license that let me waive copyright altogether, but MIT seems closest.
Good luck with porting and maintaining!
